### ISSUE TITLE
Problems with some commands when in "mpvi-seek"

### ISSUE THREAD

**Issue by Ypot** [lorniu/mpvi#15]
Some commands don't work from mpvi-seek minibuffer.

mpvi-seek i: 
`funcall-interactively: Command attempted to use minibuffer while in minibuffer`

mpvi-seek s:
`apply: Command attempted to use minibuffer while in minibuffer`

**Comment by Mercurius-Lee** [comment]
Make this setting below ,it will solve your problem.
(setq enable-recursive-minibuffers t)

**Comment by Ypot** [comment]
Working, thanks!!
