### ISSUE TITLE
Suggestions: Volume, full screen

### ISSUE THREAD

**Issue by Ypot** [lorniu/mpvi#16]
Could it be possible to control volume, from mpvi-seek minibuffer?
And to get the mpv window into full screen from mpvi-seek?

**Comment by lorniu** [comment]
You can bind the keys as you wish. 

For example. f for fullscreen, just add this to your init file:

```elisp
(define-key mpvi-seek-map "f"
            (lambda () (interactive) (mpvi-prop 'fullscreen 'yes)))
```
