### ISSUE TITLE
这里的"拉片"是指反反复复看某一段时间段的视频，还是别的什么意思?

### ISSUE THREAD

**Issue by randomwangran** [lorniu/mpvi#2]
https://github.com/lorniu/org-mpvi/blob/deb5c796aa3807c8893a7a6018cd7ec0aaa4a71a/README.md?plain=1#L19

**Comment by lorniu** [comment]
来自百度百科的回答:
> 拉片其实就是跟拉锯一样——一格一格地反复看、反复倒带（盘），同时分析纪录下你所看的、所总结的。 一格一格地看电影，深度解读电影。 然后把每个镜头的内容、场面调度、运镜方式、景别、剪辑、声音、画面、节奏、表演、机位等都纪录下来，最后总结一下。
