### ISSUE TITLE
重新打开org文件截图不刷新等问题

### ISSUE THREAD

**Issue by ajaxxor** [lorniu/mpvi#4]
今天体验了一下，有2地方体验不好

1. 插入截图时，图片会显示。关闭Emacs，再次打开这个org，图片就不显示了。开关`org-toggle-inline-images`也不行；
2. 截图的存储方式太分散了，图片不好管理。这样带来一个问题，不容易看懂那些图片是属于哪里的。比如截图了但没截好而不需要的图片也被存下来了，但不知道怎么删。浪费不少空间。
希望作者能改进一下

**Comment by ajaxxor** [comment]
![图片](https://user-images.githubusercontent.com/129724342/234275360-08207c18-a091-49b8-85df-9848acd2be2c.png)再次打开不显示图片

**Comment by lorniu** [comment]
使用 org-attachment 管理图片还是挺方便的。

如果想管理、查看图片，只需要光标放在链接上按键 `C-c C-a`，然后按照引导来就可以了：
- https://orgmode.org/manual/Attachment-defaults-and-dispatcher.html

至于你说的不能显示图片，可能是你哪个地方配置有问题，也有可能是BUG？因为正常来说，attach link和普通的 file link 没啥区别。

以后不排除会增加其他的图片存储方式，但现在有些忙、有些懒。当然，如果你安装了 org-download 的话，想定制图片保存位置，可以先通过 `C-s` 将图片复制到粘贴板，然后调用 `org-download-clipboard` (是这个 api 吧？) 将其插入到 buffer 中。
