### ISSUE TITLE
Timestamps in org. file

### ISSUE THREAD

**Issue by soilc** [lorniu/mpvi#6]
Can mpvi work with timestamps in org. file? 
Does it allow you to control the playback of a media file with millisecond precision?
Do I need to install yt-dlp if I'm not going to work with youtube?
If this is based on EMMS then what should be the configuration for EMMS?

**Comment by lorniu** [comment]
> Can mpvi work with timestamps in org. file?
> Does it allow you to control the playback of a media file with millisecond precision?

Yes.

> Do I need to install yt-dlp if I'm not going to work with youtube?

No need.

> If this is based on EMMS then what should be the configuration for EMMS?

Nothing special, just load EMMS: `(require 'emms-setup) (emms-all)`.

**Comment by soilc** [comment]
A couple of years ago I tried running EMMS + mpv on Windows. It did not work for me, and I had to use another player - mplayer. EMMS can also use vlc. Therefore, to use mpvi, I decided to directly specify mpv as the player: 
`(use-package emms
             :ensure t
             :config
             (require 'emms-setup)
             (require 'emms-player-mpv)
             (emms-all)
             (setq emms-player-list '(emms-player-mpv))
             )`
Thanks a lot! mpvi is a great tool.
