### ISSUE TITLE
`mpvi-open` not working on Windows7

### ISSUE THREAD

**Issue by soilc** [lorniu/mpvi#7]
When I run mpvi-open I've got:
Waiting c:/Users/path/file.mp4...
error in process filter: condition-case: ERR: (json-readtable-error 69)
error in process filter: ERR: (json-readtable-error 69)
error in process filter: condition-case: ERR: (json-readtable-error 43)
error in process filter: ERR: (json-readtable-error 43)
error in process filter: condition-case: ERR: (json-readtable-error 69)
error in process filter: ERR: (json-readtable-error 69)
error in process filter: condition-case: ERR: (json-end-of-file)
error in process filter: ERR: (json-end-of-file)

**Comment by lorniu** [comment]
Do all video playback have this error?

**Comment by soilc** [comment]
Yes, it appears for all videos. Also, EMMS, which previously worked with mplayer, stopped working for me.
But I have to add the following. I love the legendary Windows 7 and so I didn't use this "`winget install mpv yt-dlp ffmpeg Tesseract-OCR`". I already had EMMS installed. Also I've installed mpv using MSYS2 (https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md).
The same error messages appear when starting EMMS.
After that, I tried mpvi on two other Windows 10 and Debian 11 machines. Everything works great! However, on Windows 10 I used this procedure: "`winget install mpv yt-dlp ffmpeg Tesseract-OCR`".
Here https://github.com/lorniu/mpvi/blob/master/mpvi.el I see links to PowerShell. But how does it (emacs + PowerShell) work? On Windows 7 I have PowerShell 7.1.0, and on Windows 10 PowerShell 7.3.4. Can it influence?
Thanks a lot!

**Comment by lorniu** [comment]
It could be influenced by MPV's compile options, or powershell version, I'm not sure. I don't have Windows 7 at hand to debug it.

Powershell is used to connect to MPV daemon by named pipe, the code is simple:

  https://github.com/lorniu/mpvi/blob/master/mpvi.el#L776

Can you try to debug it yourself? Or anyone else can provide a PR?

**Comment by lorniu** [comment]
> I can't upgrade to the latest powershell on Windows 7. But an interesting thing is that when I run `mpv --input-ipc-server=\\.\pipe\mpvsocket --no-video video.mp4` in powershell I can control the player from another console (cmd) using commands like this `echo seek -13 >\\.\pipe\mpvsocket`. The same principle is used in mpvi. So verything should work?

Most likely the problem is with powershell version.

**Comment by soilc** [comment]
But I found the reason. Powershell needed a newer .NET Framework. After I installed the .NET Framework 4.8 Developer Pack everything worked!
Thanks a lot!

**Comment by lorniu** [comment]
It's great to have this problem solved.

Maybe I should improve the display of error message, it's a bit too simple at the moment.
