### ISSUE TITLE
Inserting and changing timestamps in the buffer as org-mode does ?

### ISSUE THREAD

**Issue by soilc** [lorniu/mpvi#8]
Is it possible to add the ability to insert timestamps (C - c + ...), as well as change them directly in the buffer (not in the mini buffer) in the same way as org -mode does with the Shift key and the up arrows, "down"? It would indeed be a nice integration with org -mode.
Thanks!

**Comment by lorniu** [comment]
IMO, that's too many conditions to consider and would add too much complexity. Sorry.

You can extend it yourself if you want.

Exmaple code in `mpvi-seeking-insert`: https://github.com/lorniu/mpvi/blob/master/mpvi.el#L1143
