### ISSUE TITLE
mpvi open 本地视频不生效

### ISSUE THREAD

**Issue by rLry** [lorniu/mpvi#9]
doom emacs+win11
网络视频打开正常
但本地视频minibuffer仅显示started，但并没有mpv启动

> Waiting c:/Users/L/Org/1.mkv...
Started.
Updating buffer list...
Formats have changed, recompiling...done
Updating buffer list...done
ibuffer-projectile: groups set
Commands: m, u, t, RET, g, k, S, D, Q; q to quit; h for help

**Comment by lorniu** [comment]
1. 是所有本地视频都不正常还是只有某些本地视频无法打开?
2. 在命令行下直接执行 `mpv 1.mkv` 视频是否能够播放?
3. 开启调试 `(setq emms-player-mpv-debug t)` 后执行 `mpvi-open` 有什么样的输出?

**Comment by rLry** [comment]
1-2 我排查出来了，只要路径or视频文件名中有中文、空格，就无法播放。但在命令行中直接执行 `mpv file.mkv`可以播放
3. 执行 `mpvi-open`后，中文路径下打开视频文件 输出如下
![屏幕截图 2023-06-02 113018](https://github.com/lorniu/mpvi/assets/19667685/10051cb7-8560-4e3f-9677-650ee7cd48aa)

**Comment by lorniu** [comment]
我这里在笔记本和台式机上都测了一下，不管是带空格还是中文，都能正常播放。

我怀疑是不是你在 emacs 配置中修改过编码？

**Comment by rLry** [comment]
> 我这里在笔记本和台式机上都测了一下，不管是带空格还是中文，都能正常播放。
> 
> 我怀疑是不是你在 emacs 配置中修改过编码？

是的。我注释掉自己所有关于编码的配置，启用win的beta unicode设置就能正常使用了。谢谢。

**Comment by lorniu** [comment]
> 启用win的beta unicode设置就能正常使用了

按道理不需要这一步，只需要保持 Emacs 默认的编码配置即可。你可以试试。

**Comment by rLry** [comment]
> > 启用win的beta unicode设置就能正常使用了
> 
> 按道理不需要这一步，只需要保持 Emacs 默认的编码配置即可。你可以试试。

我试过了，默认编码配置不开beta unicode，依旧仅显示started，mpv不启动。

**Comment by lorniu** [comment]
我在 Win10 下面，使用默认编码，不开 beta unicode，两台电脑都能正常使用。

看你的情况，大概也是跟编码有关。除了开 beta unicode，也可以尝试设置 `process-coding-system-alist` 试试。
